### ISSUE TITLE
USER STORY: Publish a poll

### ISSUE THREAD

**Issue by Ila-bura** [Ila-bura/My-first-Agile-project#5]
As an **administrator** I can **create a poll** so that **I can collect user feedback**

**Comment by Ila-bura** [comment]
## Acceptance Criteria
* The poll has a set template that can be customised
* Once published there is an option to edit and delete it
* The poll can be scheduled to appear on the website at a set date and time

**Comment by Ila-bura** [comment]
## Tasks
- [ ] Update the admin view: the poll design (CSS and HTML) to include a customisable template
- [ ] Add the buttons "Publish", "Edit", "Delete"
- [ ] Create a JavaScript function to set the date and time to publish the poll
- [ ] Update unit test scripts
- [ ] Test the functionality
