### ISSUE TITLE
USER STORY: Manage a poll

### ISSUE THREAD

**Issue by Ila-bura** [Ila-bura/My-first-Agile-project#6]
As an **administrator** I can **pick the expiry date of a poll** so that I can **automatically hide the poll from users**

**Comment by Ila-bura** [comment]
## Acceptance Criteria
* The poll should disappear at 11.59PM on the target date
* The admin expiry date should be 3 days after the current date
* The real estate of the poll should be reserved on the home page

**Comment by Ila-bura** [comment]
## Tasks
- [ ] Update the admin module view: the poll design (CSS and HTML) to include date picker
- [ ] Create a JavaScript function to validate the expiry date is at least after 3 days
- [ ] Create a job to check expired polls everyday at 11.59PM and hide them
- [ ] Update the controller function
- [ ] Update unit test script
- [ ] Test the functionality
